owner: Aqualunem
repo: Status

sites:
  - name: Aqualunem Studio
    url: https://aqualunem.studio
  - name: PeludAPI
    url: https://peludapi.korsinemi.link
  - name: Status
    url: https://status.aqualunem.studio
  - name: Docs
    url: https://docs.aqualunem.studio/index/
  - name: CDN
    url: https://stuff.aqualunem.studio/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.aqualunem.studio
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 💙 Aqualunem Status
  introTitle: "**Status**"
  introMessage: Bienvenido a mi página de status - Aqui puedes ver la disponibilidad de mis servicios 
  navbar:
    - title: Status
      href: /
    - title: Main
      href: https://aqualunem.studio/?ref=status.page

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
